import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Create.module.css'
import {useState, useEffect} from 'react'
import axios from 'axios';
import {useRouter} from 'next/router';

// https://www.daleseo.com/react-router-nested/ Routing 읽어보기
// https://youngjinmo.github.io/2021/08/express-crud-rest-api/

export default function Home() {
  const router = useRouter()
  const {id} = router.query
  const [board, setBoard] = useState({
    title: "",
    desc: "",
    userId: 0,
  });

  useEffect(() => {
    getBoard()
  }, [id])

  const getBoard = async () => {
    await axios.get("http://localhost:8000/board/", {
      params: {
        id: id
      }
    })
    .then(res => {
      setBoard(res.data['board'])
    }).
    catch(err => console.log(err))
  }

  const updateBoardTitle = (text)=>{
    const cp = {...board}
    cp.title = text
    setBoard(cp)
  }

  const updateBoardDesc = (text)=>{
    const cp = {...board}
    cp.desc = text
    setBoard(cp)
  }

  const modify = ()=>{
    axios.patch("http://localhost:8000/board/modify", board)
    .then(function(response){
      console.log(response);
      alert("Success to modify your post!!");
      window.location.href = `./../${id}`
    }).catch(function(error){
      console.log(error);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Exchange Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/outline_book_black_24dp.png" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Tangerine:wght@700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <div onClick = {() => {window.location.href=`../${id}`}} >Exchange Diary</div>
        </h1>
        <div className={styles.card}>
          <textarea className={styles.boardTitle} value={board.title} onChange={e=>updateBoardTitle(e.target.value)} placeholder="Title"></textarea>
          <br/>
          <textarea className={styles.boardDesc} value={board.desc} onChange={e=>updateBoardDesc(e.target.value)} placeholder="Description"></textarea>
        </div>
        <button className={styles.post} onClick={e=>modify()}>Modify</button>
      </main>

      <footer className={styles.footer}>
        <div
          onClick = {() => {window.location.href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"}}
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Diana from SPARCS
          <span className={styles.logo}>
            <Image src="/color_lens_black_18dp.svg" alt="Vercel Logo" width={22} height={22}/>
          </span>
        </div>
      </footer>
    </div>
  )
}
