import styles from '../../styles/Create.module.css'
import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'

export default function Create() {
  const [board, setBoard] = useState({
    title: "",
    desc: "",
  })

  const updateBoardTitle = (text)=>{
    const cp = {...board}
    cp.title = text
    setBoard(cp)
  }

  const updateBoardDesc = (text)=>{
    const cp = {...board}
    cp.desc = text
    setBoard(cp)
  }

  const post = ()=>{

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Exchange Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/outline_book_black_24dp.png" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Tangerine:wght@700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="../" >Exchange Diary</a>
        </h1>
        <div className={styles.card}>
          <textarea className={styles.boardTitle} value={board.title} onChange={e=>updateBoardTitle(e.target.value)} placeholder="Title"></textarea>
          <br/>
          <textarea className={styles.boardDesc} value={board.desc} onChange={e=>updateBoardDesc(e.target.value)} placeholder="Description"></textarea>
        </div>
        <button onClick={e=>post()}>Post</button>
      </main>
      
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Diana from SPARCS
          <span className={styles.logo}>
            <Image src="/color_lens_black_18dp.svg" alt="Vercel Logo" width={22} height={22}/>
          </span>
        </a>
      </footer>
    </div>
  )
}