import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exchange Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/outline_book_black_24dp.png" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Tangerine:wght@700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="./" >Exchange Diary</a>
        </h1>

        <p className={styles.description}>
          Participant :{' '}
          <br/>
          First Created at    
        </p>

        <div className={styles.grid}>
          <a href="./board/create" className={styles.addCard} style={{}}>
            <span className="material-icons md-48" style={{fontSize: '48px'}}>add_circle_outline</span>
          </a>
      
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p></p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p></p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.Instantly deploy your Next.js site to a public URL with Vercel.Instantly deploy your Next.js site to a public URL with Vercel.Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Diana from SPARCS
          <span className={styles.logo}>
            <Image src="/color_lens_black_18dp.svg" alt="Vercel Logo" width={22} height={22}/>
          </span>
        </a>
      </footer>
    </div>
  )
}
